### ISSUE TITLE
Begin compiling source files together using Browserify

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#10]
Does this make sense as a request? See how [in the demo](https://github.com/publiclab/leaflet-blurred-location/blob/master/examples/index.html#L69-L72), you still need to include `src/location_tags.js` and each other source file? The ideal is that we would be able to use Browserify and then you can link your separate source files together using `require('sourcefile.js')` -- and then we'd only need to include a single file in the HTML.

I suggested a step here that would need Browserify to be working in order to be possible: https://github.com/publiclab/leaflet-blurred-location/pull/8/files#r120509041

Maybe @aspriya and @ryzokuken and you could talk a bit about how this works in their libraries.

@aspriya is already using Browserify in https://github.com/publiclab/inline-markdown-editor#contributing -- see how it has docs as follows (which we should replicate into this repository too):

```
Make changes to the files in the /src/ directory, then run grunt build to compile into /dist/inlineMarkdownEditor.js. This will use grunt-browserify to concatenate and include any node modules named in require() statements. You'll then be able to try it out in /examples/index.html. Run grunt and leave it running to build as you go.
```

This is already set up in your Gruntfile, see: https://github.com/publiclab/leaflet-blurred-location/blob/master/Gruntfile.js

But it looks like your [/dist/Leaflet.BlurredLocation.js](https://github.com/publiclab/leaflet-blurred-location/blob/master/dist/Leaflet.BlurredLocation.js) is not compiling properly. 

Actually the tests should be running against the compiled code, not the source code; see how in this repository it's pointed at the source code (`/src/*.js`):

https://github.com/publiclab/leaflet-blurred-location/blob/master/Gruntfile.js#L41

But in `inline-markdown-editor`, it's pointed at `dist/*.js`: 

https://github.com/publiclab/inline-markdown-editor/blob/master/Gruntfile.js#L36

Just needs some tweaks to address these issues and you'll be good to start using `require()` statements!

**Comment by mridulnagpal** [comment]
@jywarren The example html page is example.html rather than index.html

**Comment by jywarren** [comment]
Really? I don't see a file there: https://github.com/publiclab/leaflet-blurred-location/tree/master/examples

**Comment by mridulnagpal** [comment]
I guess we need to merge the PR first I added a file in the PR please have
a look

**Comment by jywarren** [comment]
Complete in #7!
