### ISSUE TITLE
re-calculate coordinates when changing isBlurred

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#105]
In the demo, when you click the checkboxes to turn blurring on and off, it doesn't trigger a recalculation of the coordinates: https://publiclab.github.io/leaflet-blurred-location/examples/

That's bad because if someone checked "blur my location" then immediately saved the location, it wouldn't be blurred!

We should trigger recalculation here:

https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L201

Probably by triggering `updateRectangleOnPan()`: 

https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L232

**Comment by jywarren** [comment]
Hi, @mridulnagpal - do you have any time to try taking this one on? I'd like to complete this and release a new version!

**Comment by mridulnagpal** [comment]
On it right away !!

**Comment by jywarren** [comment]
Awesome!!!

**Comment by mridulnagpal** [comment]
Isn't it called at the end of the setBlurred method?

**Comment by jywarren** [comment]
I think we need to visually see the decimals truncated under `By entering co-ordinates` -- so there's clear feedback to the user that blurring is now on -- and to ensure that the truncated digits don't get submitted, right? Thank you, Mridul!

**Comment by mridulnagpal** [comment]
Awesome!!

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren , can i try to solve this one ? Thanks !

**Comment by jywarren** [comment]
that'd be great!!

On Wed, Feb 21, 2018 at 1:51 PM, Sagarpreet Chadha <notifications@github.com

**Comment by jywarren** [comment]
Hi! I just want to re-open this because it seems that while unchecking will return to full resolution, once you then start to drag, it gets stuck in the previous state.

**Comment by jywarren** [comment]
So when you uncheck "blurred" it shows very precise coordinates, but then dragging the map blurs the location again even though the checkbox is not checked!

**Comment by sagarpreet-chadha** [comment]
Extremely sorry !

Thats strange , the changes works fine on my local project . Will try to fix this ASAP .

**Comment by jywarren** [comment]
Np! It happens, thanks!!

**Comment by jywarren** [comment]
I believe this is still an issue -- I confirmed in the demo. @mridulnagpal would you have some time to try this and see if we can ensure the blurring of the actual numbers displayed gets shown when the blur checkbox is unchecked?

**Comment by mridulnagpal** [comment]
Sure on it!!

**Comment by mridulnagpal** [comment]
@jywarren So basically we should show full lat/lng when setBlurred is unchecked right?

**Comment by mridulnagpal** [comment]
Is this good? 
![recalculation](https://user-images.githubusercontent.com/22350740/41168892-dce737d6-6b64-11e8-9931-c753f8296a8a.gif)

**Comment by jywarren** [comment]
yeah exactly!

**Comment by mridulnagpal** [comment]
Awesome lets merge it then!!

**Comment by mridulnagpal** [comment]
Is this done?

**Comment by jywarren** [comment]
Yes!!! :+1:
