### ISSUE TITLE
bounding boxes wrong when precision is 10x

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#107]
As shown in this screenshot, when you zoom out so that the grid squares are 10x10 degrees, the bounding area gets drawn incorrectly:

![screenshot 2017-11-06 at 11 47 56 am](https://user-images.githubusercontent.com/24359/32455673-8a84a2fa-c2e8-11e7-802b-8625d0b8b918.png)

To reproduce, zoom out from the default view in the demo. 

https://publiclab.github.io/leaflet-blurred-location/examples/

The code driving this is here:

https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L219-L230

The behavior at >1.0 precision is a bit odd, since we display latitudes/longitudes rounded to the nearest 10, and this happens on the left side of the decimal. It's not a common use, probably, since that's a huge area to mark a location for, but we should still fix it -- the bounding box should fill the entire center grid rectangle.

**Comment by mridulnagpal** [comment]
I can have a go at it

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Solved in #108!
