### ISSUE TITLE
precision seems to be overall # of digits, instead of digits after '.'

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#109]
See here:

![screen shot 2018-01-16 at 2 58 24 pm](https://user-images.githubusercontent.com/24359/35009546-e02856b2-facd-11e7-8bc7-d3ba16621dd2.png)

Can we confirm and fix this? It should show the same number of decimals after the '.' for both lat and longitude. Any help appreciated!

**Comment by mridulnagpal** [comment]
Resolved!!

![image](https://user-images.githubusercontent.com/22350740/36772105-ed2d395e-1c79-11e8-8897-90a0a594c220.png)

**Comment by mridulnagpal** [comment]
Should we close this @jywarren ?

**Comment by mridulnagpal** [comment]
@jywarren Is this done?

**Comment by jywarren** [comment]
Yes I believe so.  Thanks!!!
