### ISSUE TITLE
Progress indicators for "Auto-locate me" and "Search by place name" fields

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#110]
We should display a spinner, like `<i class="fa fa-spinner fa-spin"></i>` before the button text when you press `Auto-locate me` -- and maybe one to the right of the place name field -- when it starts searching for you. Right now, it's hard to see that it's doing anything. 

The function run when geocoding a string placename is here:

https://github.com/publiclab/leaflet-blurred-location/blob/e802cdf2cd4d8c7be69cca69f96327f4bc9a1346/src/blurredLocation.js#L72

And here's where the `Auto-locate` button triggers a browser-based geocode: 

https://github.com/publiclab/leaflet-blurred-location/blob/e802cdf2cd4d8c7be69cca69f96327f4bc9a1346/src/blurredLocation.js#L143

Any help with this would be really appreciated, thanks!!!

**Comment by mridulnagpal** [comment]
On it!!

**Comment by jywarren** [comment]
Awesome, and there are a couple other issues @ebarry filed in plots2 that I
think could use some help -- if you have a little time!

https://github.com/publiclab/plots2/issues/2243


And I think there was another related to searching for country names.

**Comment by jywarren** [comment]
Yes, here! https://github.com/publiclab/plots2/issues/2187

**Comment by jywarren** [comment]
Hi! We could repeat the spinner code for the search-by-placename feature, no?

**Comment by jywarren** [comment]
Hi @sagarpreet-chadha i think this is still not working properly on publiclab.org, would you mind taking a look? Thank you!

Also, the scale slider shown in the demo (which is so nice) is also not there, so maybe when you do one, you could implement both? This would be amazing!

**Comment by jywarren** [comment]
@sagarpreet-chadha would you mind confirming that this is implemented and working on PL.org? Thank you!

**Comment by sagarpreet-chadha** [comment]
Solved here : https://github.com/publiclab/plots2/pull/4633/ .
