### ISSUE TITLE
"Get my location" input in demo should be a button, not input

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#115]
This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://publiclab.github.io/community-toolbox/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****
In the demo, the checkbox "get my location" is a bit confusing:

https://publiclab.github.io/leaflet-blurred-location/examples/

https://github.com/publiclab/leaflet-blurred-location/blob/59220e0fbab4ab3f76b53bcee936ab934458e82a/examples/index.html#L30-L31

It's a bit confusing as a checkbox, so let's turn it into a button, as in this implementation:

https://github.com/publiclab/plots2/blob/69974c9a1df9ffdc931c37e9769a7cf3f031b294/app/views/locations/_form.html.erb#L31

**Comment by amitsin6h** [comment]
would like to work on this

**Comment by jywarren** [comment]
That'd be great! I'm happy to help!

**Comment by amitsin6h** [comment]
@jywarren could help me, how to run project locally

**Comment by sagarpreet-chadha** [comment]
Hi @amitsin6h   , 
1.) Have you forked the project ? 
2.) Then run `npm install` in that directory . 
3.) Also you may need to install `gruntjs` .

Thanks :)

**Comment by amitsin6h** [comment]
@jywarren could you help to know how to run project locally

**Comment by jywarren** [comment]
Hi, if you open the index.html file in a browser, you'll be able to try it out. Hope that helps!

**Comment by amitsin6h** [comment]
@jywarren please look after the #120

**Comment by mridulnagpal** [comment]
@jywarren Is this done, or there is something to add?

**Comment by amitsin6h** [comment]
@mridulnagpal its done. @jywarren I think we should cols this issue

**Comment by jywarren** [comment]
Ah yes! If you add "fixes #____" in your PR description it'll automatically close the related issue. Thanks!!!

**Comment by amitsin6h** [comment]
@jywarren sorry from next time I will take care of this.

**Comment by jywarren** [comment]
No problem! Just a tip! 😄

**Comment by amitsin6h** [comment]
@jywarren yeah but it would have not created confusion to other user.
