### ISSUE TITLE
Unexpected map behavior while zooming and panning

### ISSUE THREAD

**Issue by ebarry** [publiclab/leaflet-blurred-location#125]
Hi Location Team!
Love this feature. I am so happy tagging myself and people by blurred location, it helps show our global community, and will help us be stronger locally! 

So that other people don't get confused by some unexpected behavior of the grid map, i captured a gif of an issue i experienced, some wayward behavior while dragging: 
![location-dragging](https://user-images.githubusercontent.com/161439/37347404-25832bfa-26a8-11e8-92f4-d50a037b85f6.gif)

I was able to replicate this behavior four times in a row. 
I was also able to work around it at least once by "not zooming in", just panning.

**Comment by mridulnagpal** [comment]
@jywarren It does not do the same with the demo, I am a little confused. How is this possible? Any ideas?

**Comment by mridulnagpal** [comment]
#129

**Comment by jywarren** [comment]
Perhaps this is because the live site is not yet at the right version. Can you ping `@icarito` about https://github.com/publiclab/plots2/issues/2625 in the chatroom? http://publiclab.org/chat

Thank you!

**Comment by mridulnagpal** [comment]
Hey @jywarren , does the update work?

**Comment by jywarren** [comment]
It seems not -- we are on `v1.1.12` here: https://publiclab.org/lib/leaflet-blurred-location/package.json

And yet when testing this out on this page (zooming out 1 zoom level and mouse-panning right), i see something very similar to what Liz documented. If we can resolve the last issue in #129 we can merge that and that may fix it, no?

**Comment by jywarren** [comment]
Published the new `v1.1.13` to both to `gh-pages` demo site AND to http://publiclab.org -- and this is REALLY GREAT. I tested a bunch of interactions and saw this solved. There are a few minor lag issues here and there but this version is a really really big improvement on all issues. Closing, but please test it out!
