### ISSUE TITLE
geocode by string UI bugs

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#128]
I documented some odd interactions using this in Firefox Android:

https://youtu.be/RIzGO3RSjuY

Three are:

1. Searching for New Delhi doesn't seem to pan the map
2. Zooming out results in a misdrawn red square
3. Finger panning then doesn't seem to work

This was on Publiclab.org and should be checked against the latest demo here! 

Needs more thorough documentation and breaking up!

**Comment by mridulnagpal** [comment]
@jywarren panning and boxes are okay in the demo but seem to break apart in the publiclab integration. Is the latest demo integrated with publiclab?

**Comment by jywarren** [comment]
Oh thanks! I think it's probably a version behind so we can try upgrading!

**Comment by jywarren** [comment]
from these changes?
https://github.com/publiclab/leaflet-blurred-location/pull/96/files

**Comment by jywarren** [comment]
oh indeed, we're on 1.1.5 instead of 1.1.12... not sure why! I'll ask
Sebastian to change this.

**Comment by mridulnagpal** [comment]
#129

**Comment by mridulnagpal** [comment]
@jywarren Is this done, or we need to add something?

**Comment by jywarren** [comment]
Yes!!!
