### ISSUE TITLE
Consider a way to quantify how blurry your location is in words

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#134]
Let's make a new function that returns the human readable resolution, so like:

"3 kilometers" or "100 kilometers"

Which corresponds to the average of grid height and width at a given latitude/longitude (since these sizes change based on latitude)

So it'd be a function that accepts:

`resolutionInWords(latLon, metric)` where latLon is a Leaflet point and metric is a boolean, default true. 

We could then use it to update a text on the demo that says "your location is blurred to within `3 kilometers` and update it when zooming happens. 

We'll need to use some conversion libraries to do this and also I bet there are some good conversion functions in the Leaflet API to look through. Let's take a first crack at it and refine!

**Comment by mridulnagpal** [comment]
For 1 lon we have 111.32km and 1 lat we have 110.57.So we can have a basic km range, for instance precision = 0 implies 110km, precision = 1 implies about 11km and so on, what do you think @jywarren ?

**Comment by mridulnagpal** [comment]
There is also a method available in Leaflet plugin
![image](https://user-images.githubusercontent.com/22350740/41201223-5c92b5ce-6cd1-11e8-8832-32f7f120914c.png)
Bottom left

**Comment by jywarren** [comment]
Oh wow! Let's look into the Leaflet conversions because it will change based on latitude -- the same precision number will be a longer distance near the equator, you know?

**Comment by mridulnagpal** [comment]
The metrics on the bottom left are provided by Leaflet only. Its Leaflet's conversion only

**Comment by jywarren** [comment]
Can you link us to the code that drives it?

**Comment by mridulnagpal** [comment]
https://leafletjs.com/reference-1.3.0.html#control-scale, I used this to add it.

**Comment by jywarren** [comment]
See if you can link to the source code for that?

**Comment by mridulnagpal** [comment]
I think its this https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Scale.js#L67

**Comment by mridulnagpal** [comment]
@jywarren Should we use this method or create one of our own?

**Comment by jywarren** [comment]
If it's possible to use this, that would be perfect. Is there API guidance
for it in the Leaflet docs?

**Comment by mridulnagpal** [comment]
This is sort of an inbuilt method which I showed in the image above. We can either use the method to get km notations on the map like the image or create a similar method to calculate km range. Here is the method to add km scale to the map. 
https://leafletjs.com/reference-1.3.0.html#control-scale

**Comment by jywarren** [comment]
looks like we can already get meters like this...

https://github.com/Leaflet/Leaflet/blob/88dd22cfe89a209d19c061a813e99669844a921b/src/control/Control.Scale.js#L71-L73

oh wait! how about this??

https://www.npmjs.com/package/humanize-distance

**Comment by mridulnagpal** [comment]
Wow!!
Humanize distance looks awesome, working on a prototype

**Comment by jywarren** [comment]
This is done, right?  🎉

**Comment by mridulnagpal** [comment]
Yes closing it
