### ISSUE TITLE
Develop other ways to describe "blurriness" amount

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#144]
Based on #134, I'd like to look at a set of words we could use to express blurriness. This may need some testing out.

Say:

| meters | urban description | rural description |
|------|------|------|
| 10 | building | house |
| 100 | block | house |
| 1,000 | neighborhood | village |
| 10,000 | district | town |
| 100,000 | county | county? |
| 1,000,000 | state, department, province | same? |
| 10,000,000 | country, region | same? |
| 100,000,000 | ?? | same? |

What do you think? We could provide a converter that accepts a distance in meters, and returns the keyword. It could have a `rural` vs `urban` parameter too, if that seems helpful?

**Comment by mridulnagpal** [comment]
Sure will look for an npm module

**Comment by mridulnagpal** [comment]
Hey @jywarren tried to look for some libraries, couldn't find anything. We can create a dictionary which can be like the table you have made above

**Comment by jywarren** [comment]
That sounds good; do the words I used make sense to you if you try looking
at a few places around the world at those zoom levels?

**Comment by mridulnagpal** [comment]
Something like this?
![blurry-scale](https://user-images.githubusercontent.com/22350740/42137418-4cde91a2-7d89-11e8-9a67-ee7722cd3ca8.gif)

**Comment by mridulnagpal** [comment]
@jywarren Should we close this?
