### ISSUE TITLE
Slider-based precision slider

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#146]
Here's one more interface we could use to make location entry easy -- a slider, like:

`building -----|-----|-----|---O-|-----|-----|-----|----- country`

I bet there are some nice slider UI libraries we could use! What do you think?

**Comment by mridulnagpal** [comment]
@jywarren Looks good should we go with this one?

**Comment by jywarren** [comment]
I think either will need some modifications... like, it'd be great to actually show the words "building" and "country" on the slider, you know? But let's start with just a zoom slider at all. Want to try one of these and upload a gif?

**Comment by mridulnagpal** [comment]
Sure, on it!!

**Comment by mridulnagpal** [comment]
@jywarren Tried setting it up but having some issues can we try this one? https://github.com/kartena/Leaflet.zoomslider

**Comment by jywarren** [comment]
Sure, or do you think you could use a separate slider library outside the
map and just treat it as a different component? Looking for general jQuery
sliders?

**Comment by jywarren** [comment]
This is looking great as of #149 -- i think we should rejigger the slider so the displayed number is actually the zoom level though?

**Comment by mridulnagpal** [comment]
@jywarren Did you look at the bug I told you about? Both upper and lower commands are working. The middle command also works separately, but it doesn't work in the integrated code

**Comment by jywarren** [comment]
Hmm, can you show line numbers? What method exactly isn't working?

**Comment by jywarren** [comment]
Also pushed this to `gh-pages`!

**Comment by jywarren** [comment]
https://publiclab.github.io/leaflet-blurred-location/examples/

**Comment by mridulnagpal** [comment]
@jywarren Looks awesome!!!
