### ISSUE TITLE
add link of Publiclab.org

### ISSUE THREAD

**Issue by avsingh999** [publiclab/leaflet-blurred-location#154]
add link https://publiclab.org
![sai](https://user-images.githubusercontent.com/25536022/46331593-371d4980-c636-11e8-9ec3-b948ba129f10.png)

### code link
https://github.com/publiclab/leaflet-blurred-location/blob/881799ae0596e064577d6eb600c1ff6b36807e89/examples/index.html#L31

**Comment by vsk4** [comment]
Hello, I would like to work on this issue.

**Comment by jywarren** [comment]
please do!
