### ISSUE TITLE
Remove Geocode log

### ISSUE THREAD

**Issue by rexagod** [publiclab/leaflet-blurred-location#168]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**:  Remove the following snippet that currently generates an unnecessary log.

![logmapmodule](https://user-images.githubusercontent.com/33557095/51497877-886e6600-1dea-11e9-849f-e319a95459cd.png)

https://github.com/publiclab/leaflet-blurred-location/blob/369274989869515579d567e1c3376d9db2321dfe/src/core/Geocoding.js#L60
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by mdquigley** [comment]
Hi, I'd like to claim this issue if available please.

**Comment by mdquigley** [comment]
Hi, just following up on this issue & pull request. Apologies if I've not done so properly, please let me know if that's the case!

**Comment by gauravano** [comment]
Hi @mdquigley,  we would be happy to help you in any case, but you need to give your PR link here or refer the issue as Fixes #[issue-number] in your PR. Thanks!

**Comment by mdquigley** [comment]
thanks @gauravano, I added the FIxes#[issue-number] tag to the PR.

**Comment by suryanshsrivastava** [comment]
Can I take up this issue as my first PR ?

**Comment by gauravano** [comment]
Hey @suryanshsrivastava, this issue is solved in #169 but the issue remained open due to missing `Fixes [issue-number]` statement in the PR's main comment. Sorry for the inconvenience. You can see more issues at https://code.publiclab.org/#r=all and if you can't find any open there, feel free to comment here. We'll try to open one for you or point you to some good-first-issue. Thank you!

**Comment by gauravano** [comment]
Hey @mdquigley, thanks for adding fixes statement to your comment mike but for auto-closing of the issue on PR merge to work, you need to add the fixes statement in PR's main comment, which in your case is this one - https://github.com/publiclab/leaflet-blurred-location/pull/169#issue-246450695 . (Just a good practice suggestion). Thank you!
