### ISSUE TITLE
Add a getPrecision() method showing # of decimals current grid is showing

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#17]
So if the grid drawn is to 44.001 precision, `.getPrecision()` would return `3`. This should have a test written to it -- zoom the map with a Leaflet command, and check that the precision has changed!

It can be calculated based on the zoom level of the map, and should match the grid drawn by the Grid system (detailed in #18). 

As the map is zoomed in and out, the precision will change (as shown in the displayed grid).

**Comment by mridulnagpal** [comment]
@jywarren Is there anything left of this issue?

**Comment by jywarren** [comment]
Just documenting it in the README?

**Comment by mridulnagpal** [comment]
Is this done?

**Comment by jywarren** [comment]
👍
