### ISSUE TITLE
Make "Obscure my exact location" toggle the grid on and off

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#19]
and also set `blurredLocation.isBlurred` to `true` or `false`. We can do this via a tested method called `blurredLocation.setBlurred(boolean)` which toggles the grid and sets `isBlurred`. Make sense?

**Comment by mridulnagpal** [comment]
Is this done?

**Comment by jywarren** [comment]
Yes, i think -- does it toggle isBlurred? Then yes!

**Comment by mridulnagpal** [comment]
Yes we have a test for that as well.

**Comment by jywarren** [comment]
perfect, all good!

**Comment by mridulnagpal** [comment]
Closing the issue then, one more off the list!!

**Comment by jywarren** [comment]
:-) Great work!
