### ISSUE TITLE
add an onDrag() method to blurredLocation

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#20]
That will:

1. trigger when the map moves for any reason -- using a Leaflet event listener (http://leafletjs.com)
2. use `getLat()` and `getLon()` to find the placename using `getPlacenameFromCoordinates()` and display it in the "In Text" input in the example: https://publiclab.github.io/leaflet-blurred-location/examples/
3. use same methods to fill `By giving co-ordinates` inputs

**Comment by jywarren** [comment]
After #36 this is probably next. Great work!

**Comment by mridulnagpal** [comment]
Actually I am working on this currently, will take a few more minutes, then I'll be on with #36

**Comment by jywarren** [comment]
Great.
