### ISSUE TITLE
adapt getLat() and getLon() to truncate to the result of getPrecision()

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#21]
`getPrecision()` -- mentioned in #17 -- will let us truncate the decimals of the locations before passing them. This is the main purpose of `leaflet-blurred-location`! :-)

**Comment by mridulnagpal** [comment]
@jywarren I think this one is completed as well, what do you say?

**Comment by jywarren** [comment]
Can you add a section to the README explaining that these are truncated to
the current precision?

Over here: https://github.com/publiclab/leaflet-blurred-location/#options

**Comment by mridulnagpal** [comment]
On it

**Comment by mridulnagpal** [comment]
Is this done?
