### ISSUE TITLE
Add new functions to README

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-blurred-location#225]
New functions to add to README:
getZoomByPrecision(precision)
setZoom(zoom)
getZoom()
getPrecisionFromNum(num)

**Comment by jywarren** [comment]
Hooray!!!

**Comment by preetiy** [comment]
hey! is this issue still open to contribute?

**Comment by nstjean** [comment]
@preetiy This was already merged and should be closed it looks like! There are other available issues though, are you looking for a first-time-only issue?
