### ISSUE TITLE
Weekly community Check-In #42 - Happy Holidays

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/leaflet-blurred-location#227]
Hi everyone 👋

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Happy Holidays
I would like to thank everyone for helping grow the community and contributing to PublicLab this year. Merry Christmas :christmas_tree: :santa: to everyone celebrating Christmas and Happy holidays :tropical_drink:  to everyone else :)

## This week's focus Issues

These are issues that are of high priority and requests from our 
large community that use the software. We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these. Or you can add more context to the ones labeled `gci-candidate` so that they can be taken up by the gci folks.  We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance :smile: 

https://github.com/publiclab/Leaflet.DistortableImage/labels/high-priority

## Next Check-in

If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time :smile: 

**Thanks everyone for making Public Lab awesome** :balloon: 
Have a great week ahead all :heart:

**Comment by cesswairimu** [comment]
@dmahajan980, @bryceparkman, @dependabot-preview[bot], @nicoleiocana, @0dim, @Uzay-G, @nstjean, @AnshitaVishwa, @tsparksh, @sharmamansi, @polygonart6777, @anthony-zhou, @cesswairimu, @chen-robert, @leesgrey, @smarty1palak, @VladimirMikulic, @nfarve, @jywarren, @chanchalsaini, @johnaceto, @gireeshcse, @lisaschumann, @shashwataggarwal, @yeo-yeo, @gabrielrumiranda, @mikepetridisz, @GarvinH, @Ugtan, @sap143, @arjunshekhawat5, @sagarpreet-chadha, @ami-friedman, @gautamig54, @shubhankarsharma00, @rebecarancan, @swathi-0901

**Comment by cesswairimu** [comment]
@Rishabh570 @sashadev-sky @IshaGupta18 @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo

**Comment by VladimirMikulic** [comment]
Happy holidays everyone :tada:

**Comment by SidharthBansal** [comment]
Happy holidays!!!! :-)))

**Comment by dmahajan980** [comment]
Happy holidays everyone!!

**Comment by Uzay-G** [comment]
Happy holidays and have a happy new year! :smile: 
I am learning a lot through some design tasks that are really fun and I am also having fun working on some testing for plots2.

**Comment by alaxalves** [comment]
Happy holidays everyone! I've been working on Spectral Workbench, just made some improvements there in our docker environment and redesigned our continuous integration pipeline. I realized there are a few tests breaking that need some refactoring. I'll continue to work on that!

**Comment by nstjean** [comment]
Happy holidays! I can't believe the year is almost over. :open_mouth: Last week I was working on the /post/ form, LBL, and implementing a zoom powertag across the site. This week I'm finishing that up and moving into working on the /map/ route!

**Comment by jywarren** [comment]
Hi all! HAPPY HAPPY NEW YEAR! 🎉 🎉 🎉 

I am merging a LOT of PRs today. So much progress. Thank you all so much for a very wonderful 2019, and looking forward to 2020!!!

**Comment by blurry-x-face** [comment]
Happy New Year Everyone!!

I recently started working on image sequencer, this week I tried adding Color-Dodge blending method in Blend module.

**Comment by mikepetridisz** [comment]
Happy New Year! 🎉

**Comment by shipcy** [comment]
Hey, everyone! My name is Shipra Choudhary. I'm currently a junior pursuing Computer Science and Engineering from India. My skill set includes HTML, CSS, Bootstrap, Javascript, JQuery, C++, MySQL, etc. And I'm new to open source and I'm working on my first contribution. So, please help me out.

**Comment by Uzay-G** [comment]
Hey @shipcy! If you ever have any questions you can always ask me :+1:. You can also talk to on our [Gitter channel](https://gitter.im/publiclab/publiclab)

**Comment by cesswairimu** [comment]
Hey @shipcy, welcome...glad to have you here.
Moved to https://github.com/publiclab/community-toolbox/issues/308. Thanks everyone

**Comment by VladimirMikulic** [comment]
@shipcy @Uzay-G and I are available 24/7 so feel free to ask for help.

**Comment by cesswairimu** [comment]
Thanks @Uzay-G  and @VladimirMikulic  :heart:

**Comment by shipcy** [comment]
Thank you so much @Uzay-G , @cesswairimu and @VladimirMikulic .
