### ISSUE TITLE
Add onSubmit handlers to lat/lon inputs on example

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#23]
Make it so that when you enter a latitude in the latitude input and press return, it runs `blurredLocation.setLat(latitude)` which runs `blurredLocation.panMap()`.

I noticed a bug also where `panMap` calls `map.panTo()` but that needs to be `options.map.panTo()`.

**Comment by mridulnagpal** [comment]
Is this done?

**Comment by jywarren** [comment]
yep!
