### ISSUE TITLE
Weekly community Check-In #50 - Favorite text editors

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/leaflet-blurred-location#237]
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Favorite Text editors :spiral_notepad: 
Lets all this week mention a text-editor we use and what we love about it..It might give another contributor curiosity to checkup another editor, give a thumbs up if you also use a text editor mentioned. 

## 2020 Software Contributor Community Survey Open :tada: 
Don't forget our contributor community survey is still open! 
Survey ticket is here: #7406

Please give us your thoughts in this anonymous form -- we'll post the results at the end and we can all learn about ourselves! We'll keep it open until March 27, 2020 https://forms.gle/Z6J3Mrdszm9iFiuv9

## Call for Gsoc Proposals
We are participating in GSoc under DIAL, all applicants looking to apply for the internship with PublicLab, we also ask you to submit your proposal on the PublicLab website.
https://publiclab.org/notes/cess/03-02-2020/call-for-2020-soc-proposals-gsoc-and-outreachy
If we get accepted to Outreachy, the proposals should also be posted on the same link :point_up: 
 Be sure to submit early and post a link on gitter so that contributors can give feedback. 

## Next Check-in
If you would like to open the next weekly check-in please comment below..I am glad to guide you if its your first time or have any questions.

Thanks everyone for making PL awesome and have a great week ahead :balloon:

**Comment by cesswairimu** [comment]
@Nevenem, @chirag-wadhwa, @Tlazypanda, @yogeshjdeshmukh, @omizrahi99, @cesswairimu, @theOpetunde, @sailahonkanen, @robin-natale, @avidler, @nstjean, @keshavsethi, @NitinBhasneria, @ccyccyccy, @sssash18, @JordanTFite, @krsudhanshu, @3ng7n33r, @Odisseuss, @imajit, @VladimirMikulic, @rehasantiago, @urvashigupta7, @HashTalmiz, @vinitshahdeo, @dragonwarp, @z-arnott, @JanviMahajan14, @mantinone, @DouglasLutz, @seabl, @jywarren, @crisner, @Uzay-G, @shaibrown5, @kostogls, @pcube99, @nicoleiocana, @simonastefan, @giovannyg

**Comment by cesswairimu** [comment]
@Rishabh570 @sashadev-skyl @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by sidntrivedi012** [comment]
Hey all,

Though I have been a big fan of Vim but currently I use VSCode due to its awesome developer ecosystem with Vim keybindings in order to get the flow Vim offers. 😃

Here's a nice video ( https://youtu.be/uininbruNx4?list=PL8tzorAO7s0jy7DQ3Q0FwF3BnXGQnDirs )about neovim and also thoughbot's videos are best for both Vim as well as Emacs. 💻

**Comment by alaxalves** [comment]
Hi all, 
I'm with @sidntrivedi012, Vim is great when I'm in a server and need speed keybinding, but VSCode is "the man" when it comes to developing time taking features. 
For this week I'm focused on some PR at Spectral Workbench, regarding the Travis pipelines and Docker dev env.

**Comment by nstjean** [comment]
I'm currently using VSCode and I'm liking it. But in the past I used Sublime for a little while and before that I used Edit++ for many many years. My only requirement is that I have a good light theme. :wink: 

This week I'm finishing up our Outreachy map project in plots2, LEL and LBLD! It's so nice to see it coming together and working!

**Comment by jywarren** [comment]
Hi all, today I'm doing code community coordination, so am syncing up with PL staff and spending the day catching up! Missed you all!

I'm a vim user after a year or two of emacs back in the day. Before then I used TextMate, which I'm not sure exists anymore? Dunno! But i loved it! :keyboard: :man_technologist:

**Comment by HarshKhandeparkar** [comment]
I have used many editors like sublime, brackets, atom and even nano on a raspberrypi. But there is something about vscode that just makes it seem like the best one out there. Maybe it is the marketplace, maybe the code completion. Idk, but it is probably the best code editor for javascript (considering its size and that it is not a full fledged IDE).

I still use atom when I write bash scripts though. The atom github interface is a thousand times better than that of vscode. That's the only reason why I use it.

I use the Hack font for my editors, it's pretty cool and distinguishes between characters like 1, l, I very well.

Also the extension bracket pair colorizer is really helpful when writing a long file.

**Comment by Rishabh570** [comment]
I use VSCode and I love it because of the features it brings to the table and keyboard shortcuts are just cherry on top :smile: 
I'm currently planning out the support for the GitLab adapter in community-toolbox.

**Comment by govindgoel** [comment]
I have used Vim,Atom, VSCode, Intellij Idea, But VSCode standout for javascript among other editors also Atom provide a great interface for github.

**Comment by sagarpreet-chadha** [comment]
I plann on reviewing the proposals till weekend and syncing up with outreachy fellows. Thanks :balloon:

**Comment by crisner** [comment]
I use vscode. I like it because of the in-built editor and theme availability. I also like the vscode marketplace where you can browse for extensions and themes. Among the many test editors I have tried I liked vscode the best.

**Comment by cesswairimu** [comment]
I have been using vim for the past 5 years because I am in love with the terminal :wink: ,  before that I used Sublime text, I aslo use Vscode's Live share when collaborating remotely since cloud9 went under

**Comment by nstjean** [comment]
@cesswairimu Wow! That seems pretty wild to me!

**Comment by cesswairimu** [comment]
Yeah sure is @nstjean but once you get a hang of it its hard to go back :smile:

**Comment by cesswairimu** [comment]
Anyone interested in opening this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/infragram/issues/102 Thank you everyone
