### ISSUE TITLE
Change getPlacenameFromCoordinates() to be asynchronous and use a callback handler

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#24]
`getPlacenameFromCoordinates()` is not working because it makes an AJAX call and that runs asynchronously:

```js
  function getPlacenameFromCoordinates(lat, lng) {
    var loc = "Location not found";

    $.getJSON("https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+lng, function(data) {
      if (data.results[0]) {
        loc = data.results[0].formatted_address;
      }
    });
    return loc;
  }
```

https://github.com/publiclab/leaflet-blurred-location/blob/master/src/core/object.js#L78-L87

At the time it wants to return `loc` the response hasn't come back yet. So we need to pass it a function to be run on completion, and you can tell it what to do with the location string there:

`getPlacenameFromCoordinates(lat, lon, callback)`

the callback can be anything, even `alert()` -- so:

`getPlacenameFromCoordinates(10, 40, alert)` would pop up an alert with the result.

**Comment by mridulnagpal** [comment]
@jywarren I tried using callback but I couldn't get it right, so I tried using sync call, please have a look.

**Comment by jywarren** [comment]
@ccpandhare has worked on this kind of thing; can you offer some advice?

**Comment by jywarren** [comment]
Is this complete then? I don't see any particular bug in usability from it?
