### ISSUE TITLE
move input listeners into separate UI section of code

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#30]
The code for #23 and #25 is really just the interface, not the core functionality of the library. We should move it into a submodule called Interface.js and require it into `BlurredLocation.Interface` to keep our code better separated and organized.

**Comment by jywarren** [comment]
Is this complete? I think you need to move the obscureLocation() method out into the example, since it's interface code and not universal -- it's dependent on the specifics of the HTML you create.

**Comment by mridulnagpal** [comment]
Is this done?

**Comment by jywarren** [comment]
Left a comment and request there. Thanks!
