### ISSUE TITLE
add getFullLat() and getFullLon() methods and document difference from getLat()

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#38]
https://github.com/publiclab/leaflet-blurred-location/#options should show how the normal `getLat()` is truncated to the current map zoom level-based precision (as reported by `getPrecision()`). 

Also tests to show that this is true! Thanks!

**Comment by jywarren** [comment]
This exists but I noticed only one of the two has a parseFloat, getFullLon doesn't. How is it passing tests?

**Comment by mridulnagpal** [comment]
getCenter() function returns an int that's why, corrected the issue in graticule PR only!
