### ISSUE TITLE
add setZoomByPrecision() method

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#44]
Precision is set by zoom, so to set precision, we can just zoom to a specific level for now. 

But soon, a `setZoomByPrecision()` method would be great, so you could go to a precision you intend.

**Comment by mridulnagpal** [comment]
On it

**Comment by mridulnagpal** [comment]
Do I start from a default zoom, then keep on increasing it in a loop till we get the required precision

**Comment by mridulnagpal** [comment]
Can you tell me how do we do it, either loop or do some calculations using Leaflet methods?

**Comment by jywarren** [comment]
Hm, this is a good question. I'm not sure... I think there's some math we could do to calculate this out, but it's not extremely high priority so we can wait on it for a bit. I'm also just not great at math :-P

**Comment by mridulnagpal** [comment]
This one's complete as well
