### ISSUE TITLE
add getPlacename() method to public API

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#49]
We shoudl be able to get a string description of the placename, and I believe this already exists -- let's document it in the README and expose it in the public API if it's not already.

**Comment by jywarren** [comment]
This is distinct from `getPlacenameFromCoordinates()` -- it should just get current placename by running `getPlacenameFromCoordinates(getLat(), getLon())`

**Comment by mridulnagpal** [comment]
Its already there in the public API we can access it using a callback function

**Comment by jywarren** [comment]
Can you document in the readme? Thank you!

**Comment by mridulnagpal** [comment]
should we close this?

**Comment by jywarren** [comment]
Yep!
