### ISSUE TITLE
Test that .getLat() and .getLon() change after map.setView()

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#5]
Let's add a test that ensures that the methods `.getLat()` and `.getLon()` change after the Leaflet map is interacted with. We can simulate this in tests with `map.setView([lat, lon], zoom)`:

```js
map.setView([51.505, -0.09], 13);
blurredLocation.getLat() == 51.505;
```

Later, we should ensure that it returns that value, but truncated to the current precision/zoom level, so:

```js
var object = new basic.BlurredLocation({
  lat: 41.01,
  lon: -85.66
});
blurredLocation.getLat() == 41.01;
map.setView([51.505532, -0.092362]);
expect(blurredLocation.getLat()).toBe(51.50);
```

In general, testing could use a lot of Leaflet features: http://leafletjs.com/examples/quick-start/

(this can be broken out into a separate issue)

**Comment by mridulnagpal** [comment]
@jywarren On it

**Comment by mridulnagpal** [comment]
@jywarren What's blurredLocation? Is it an instance of BlurredLocation? If it is shouldn't it be named object? Little confused.

**Comment by jywarren** [comment]
Hi, yes, it is - and actually, I think it's best to name the instance this way -- it's a convention you'll see in other libraries. I'll leave a comment to this effect on #3 too.

**Comment by mridulnagpal** [comment]
@jywarren For this will I have to add an event listener that whenever setView is called any instance of class BlurredLocation will change it values to the same??

**Comment by mridulnagpal** [comment]
@jywarren If you can give a green flag I will start working on it. Thanks

**Comment by jywarren** [comment]
Ah, sorry - yes, that sounds right -- but maybe there's a more general event than `setView`? See docs: http://leafletjs.com/reference-1.0.3.html

OR, maybe more efficient is that since getLon/getLat are methods, you can just look up the current Leaflet map center when they're called, rather than doing it all the time?

**Comment by mridulnagpal** [comment]
The map won't work till there is a map container tag div with id "map". Do I need to create it using javascript only? for tests atleast?

**Comment by jywarren** [comment]
You should be able to use a minimal test html template - see how they're
created in PublicLab.Editor... they're stored in a folder inside the spec
folder.

**Comment by mridulnagpal** [comment]
I used the fixture template and it works well, thanks. Moreover I added the build button and the tests you have mentioned above. Please have a look #3

**Comment by mridulnagpal** [comment]
I think this issue is done, what say @jywarren ?

**Comment by jywarren** [comment]
Great!
