### ISSUE TITLE
expose Leaflet map object in public API

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#50]
via `blurredObject.map`

and document this in the README -- so people can directly send Leaflet commands to the map. 

Thanks!

**Comment by mridulnagpal** [comment]
This is done in the graticule integration PR itself!

**Comment by jywarren** [comment]
Great, however in the future lets keep the PRs separate so we can do one thing per PR -- thanks! But yes i saw that and it looks super. :-)

**Comment by mridulnagpal** [comment]
Should we close this?

**Comment by jywarren** [comment]
+1!

On Jul 9, 2017 2:38 PM, "Mridul Nagpal" <notifications@github.com> wrote:

Should we close this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/leaflet-blurred-location/issues/50#issuecomment-313937394>,
or mute the thread
