### ISSUE TITLE
preserve input placename string and return it if it exists instead of a reverse geocoding

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#59]
Let's save the input placename as a string, and return that, as `location.placename`, but if there's no input placename, then we fall back to reverse geocoding? So we'd have `getPlacename()` which returns `location.placename || location.getPlacenameFromCoordinates(...)` -- make sense?

Followup to #58

**Comment by mridulnagpal** [comment]
#60 Please have a look works fine on my remote
![image](https://user-images.githubusercontent.com/22350740/28715071-f4c72950-73b3-11e7-8487-0d26220b938d.png)

**Comment by jywarren** [comment]
Hmm, are you sure you updated it? I see this:

![screenshot 2017-07-28 at 3 09 42 pm](https://user-images.githubusercontent.com/24359/28732704-27c0253a-73d9-11e7-8fd1-e819c751e215.png)

Great work though -- this is good progress!

**Comment by mridulnagpal** [comment]
Just a sec, I'll push it to gh-pages as well

**Comment by mridulnagpal** [comment]
Pushed, please have a look

**Comment by jywarren** [comment]
Perfect. Merging!

**Comment by jywarren** [comment]
Done! Great.
