### ISSUE TITLE
Integrating add grid to BlurredLocation object

### ISSUE THREAD

**Issue by mridulnagpal** [publiclab/leaflet-blurred-location#6]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Problem #
We need to integrate a file of code to an object, to avoid including it in our html pages. We are creating an object which you will find here https://github.com/publiclab/leaflet-blurred-location/blob/master/src/object.js. We need to add a new method to this object which would add a grid to the existing map.

# Solution #
At first set up the repo and test the repo using https://github.com/publiclab/leaflet-blurred-location/blob/master/examples/index.html. Now you need to take the method from https://github.com/publiclab/leaflet-blurred-location/blob/master/src/locationForm.js named addGrid and make it a method of the object we will be creating here https://github.com/publiclab/leaflet-blurred-location/blob/master/src/object.js.

It will be something like adding
`this.addGrid = function(map) {
// All the stuff from locationForm.js
}`

## Steps to fix ##

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

**Comment by jywarren** [comment]
Looks like @akshat14714 has claimed this!
