### ISSUE TITLE
ensure displayed coordinates are truncated to precision

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#61]
under `Option 3 : By giving co-ordinates` -- thanks!

**Comment by jywarren** [comment]
Let's do this next!

**Comment by mridulnagpal** [comment]
On it!

**Comment by mridulnagpal** [comment]
Actually these are the co-ordinates entered by the user so we don't display these, so most we can do is setZoomByPrecision as it is entered by the user, for instance if one inputs 43.23 and -85.54 we pan to the location and set precision as 2

**Comment by jywarren** [comment]
Yes but we can overwrite them in the demo code, even if we don't change the
library code. How's that?

**Comment by mridulnagpal** [comment]
I didn't get it, can you give an example of the scenario?

**Comment by jywarren** [comment]
I mean could you overwrite the inputs using getLat and getLon if the user
interacts with the map or the text-based search?

**Comment by mridulnagpal** [comment]
Yes can be done, on it!

**Comment by mridulnagpal** [comment]
This one's resolved in #67

**Comment by jywarren** [comment]
+1!
