### ISSUE TITLE
display a marker instead of box when `Obscure my exact location` is unchecked

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#62]
i.e. when `isBlurred` is `false`

Thanks!

**Comment by jywarren** [comment]
And this too! The rectangle need not be displayed if isBlurred is false. Thanks!

**Comment by mridulnagpal** [comment]
The sync part is done, working on the marker thing.

**Comment by mridulnagpal** [comment]
Marker has also been added, will push it to gh-pages in minutes.

**Comment by mridulnagpal** [comment]
![image](https://user-images.githubusercontent.com/22350740/28752233-f25bf67a-7537-11e7-9f35-bfa34891d14b.png)

**Comment by jywarren** [comment]
Great!
