### ISSUE TITLE
Truncate placename if isBlurred == true

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#63]
this one is harder -- because it's difficult to semantically determine what to display as text for a highly blurred location. 

My suggestion is that we come up with some kind of manual mapping, like:

```
1: country
0.1: state/province
0.01: city
0.001: city
```

maybe we look at what different fields the geocoder returns, and assign a zoom range for each, kind of like how we did for the zoom levels and precisions?

We may want to decide for example that the text description never gets better than "city" -- and we'll want to test this out by looking at a lot of places to be sure the text description doesn't give away more than the blurred coordinates. 

Does this make sense?

I think we'll need a `getBlurredPlacename()` method to perform this work.

**Comment by mridulnagpal** [comment]
Sounds really interesting, on it!!

**Comment by mridulnagpal** [comment]
@jywarren What was the api key for geocoding for PublicLabs?

**Comment by jywarren** [comment]
Hmm, do you need it? Aren't you already reverse geocoding to get the
placename?

**Comment by jywarren** [comment]
Here you can explore the different returned placename values:

 https://github.com/publiclab/leaflet-blurred-location/blob/master/src/ui/Interface.js#L31

**Comment by jywarren** [comment]
But let's perform the truncating in getPlacename, not in the interface code, since it's a core functionality that doesn't depend on interface. So here: https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L104

**Comment by mridulnagpal** [comment]
Actually there is an options for getting only the country name or city name in google reverse geocoding but it is asking for a key. Here 
![image](https://user-images.githubusercontent.com/22350740/28755382-5c5bd7cc-7577-11e7-9abc-9fa2a6f40e92.png)

**Comment by jywarren** [comment]
Ah, I see. So we'll have to make this optional, perhaps.

**Comment by jywarren** [comment]
Wait, what's a client ID? Could we supply that instead? I just don't want
to put our API key into the repository.

**Comment by jywarren** [comment]
So, if we do need to make it optional we could have a constructor parameter
like blurPlacename and googleApiKey -- and include a warning in the readme
that without an API key or client ID (linking to the docs you cited)
getPlacename may reveal more location than intended.

 This warning is really important since people may rely on this library to
protect their privacy. Make sense?

Thanks!

**Comment by mridulnagpal** [comment]
Sure can be done, on it!

**Comment by mridulnagpal** [comment]
@jywarren I tried using the result_type feature in geocode but it doesn't show any result in many cases, figuring out another way to do so

**Comment by mridulnagpal** [comment]
@jywarren I made some more changes in #67 and at precision 0 it displays the country, will post a new PR for the rest.

**Comment by jywarren** [comment]
Thanks, will look for it!

**Comment by jywarren** [comment]
Also perhaps we should separate any additional work on this into a separate PR -- best not to mix. Sounds good, and if you could copy in and/or respond to my comments on #67 that are relevant to the next PR, that would be great.

**Comment by mridulnagpal** [comment]
Any more changes needed regarding this issue?

**Comment by jywarren** [comment]
I published to the publiclab GH pages and I'm occasionally seeing
"undefined" in the country field. Also there could be an extra space
between postal code and country. But very very close!

**Comment by mridulnagpal** [comment]
On it!!

**Comment by mridulnagpal** [comment]
Posted a PR please have a look !!

**Comment by mridulnagpal** [comment]
Any more changes required?

**Comment by jywarren** [comment]
I think we're good for now.

**Comment by jywarren** [comment]
Can we update this to clarify the exact correlation between zoom and precision and human-readable placename? See how in my most recent README explanations, i walk through the relationship between precision and decimal places and zoom level; we could do the same (with a table of what precisions relate to what human readable location "scales" like city, state, country) for this. We should probably start by making a table which lays out the available human readable place names, so we can propose appropriate precision values for each. Make sense?

**Comment by jywarren** [comment]
Moving to documentation issue in #98
