### ISSUE TITLE
stop including Leaflet in via require()

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#66]
I was thinking about this, and in the most common use cases, people will already have Leaflet included in their HTML -- so I think we should just assume it's already there, and not compile it in. So this would require changes to the examples `.html` files, and the line in the main file is:

https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L3

**Comment by mridulnagpal** [comment]
So I include it in the html file itself?

**Comment by jywarren** [comment]
Yep. But please post about the new demo first, this isn't as critical as
getting some input and showing people your work!

**Comment by mridulnagpal** [comment]
On it!

**Comment by mridulnagpal** [comment]
I have posted a research note as a start, can you tell me what other things should I add there?

**Comment by jywarren** [comment]
Sounds great -- they asked some questions -- sounds like they loved it!

**Comment by mridulnagpal** [comment]
Cheers !! :smile:
