### ISSUE TITLE
offer to use browser-based geocoding (by IP) with geocodeWithBrowser()

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#69]
but be sure it's blurred if need be. 

And add a button to the demo, maybe as a link just above "Blur my location"?

Thanks!

**Comment by jywarren** [comment]
as in https://github.com/publiclab/mapknitter/blob/master/app/views/maps/_geocoder.js.erb

**Comment by mridulnagpal** [comment]
I didn't get it, the link you posted. Where does it geocode using the location of the browser?

**Comment by jywarren** [comment]
Info here -- thanks! :-)

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
