### ISSUE TITLE
Update lat/lon/placename fields when you use the map

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#73]
This seems to be broken in the demo when you don't initially enter a location. 

https://publiclab.github.io/leaflet-blurred-location/examples/

**Comment by mridulnagpal** [comment]
Actually I made it as an option initially turned off, we can enable it using `blurredLocation.Interface.enableLatLngInputTruncate()`, keeping it as default in the PR #67

**Comment by mridulnagpal** [comment]
Should we close this as well?

**Comment by jywarren** [comment]
Yep! Awesome.
