### ISSUE TITLE
Add explanatory text

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#74]
> Your exact location won't be posted, only the grid square it falls within will be shown. Zoom out to make it harder to tell exactly where your location is. [Read more about this privacy system](https://publiclab.org/wiki/location-privacy)

Also by the map, we shoudl show:

> Drag the map to change your location and the amount of blurring.

**Comment by mridulnagpal** [comment]
@jywarren I couldn't open the link that you have posted. It says the page has not been created yet, and you need to login to create one.

**Comment by mridulnagpal** [comment]
I have updated the readme file in a new PR, added a privacy section in the features part, please have a look!!
