### ISSUE TITLE
Disable scroll panning -- scroll wheel should only zoom, not pan

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#75]
This caused some confusion in tests with a friend of mine -- when using trackpad pinch or scroll gestures, it recenters the map and makes it really easy to lose your location when you zoom out too far and then back in using a pinch gesture.

But regular panning with drag should still work. This is a bit weird but I think it'll make it more usable. We can search for "Disable Leaflet pinch to pan" or "Lock location while pinch zooming" and such to see if this is a configurable option of Leaflet maps. 

Another way to put this is that pinch-zooming or scroll-zooming should treat the center of the map as the point to zoom upon, not the position of the gesture (or the mouse).

**Comment by mridulnagpal** [comment]
Done #77

**Comment by jywarren** [comment]
Super!! @kindanduseful - check it out -- https://mridulnagpal.github.io/leaflet-blurred-location/examples/

**Comment by mridulnagpal** [comment]
Is there anything left of this issue?

**Comment by jywarren** [comment]
I wonder if you could add the pinch gesture as I don't think that's working
the same as scroll. I think it's a different leaflet event.

**Comment by mridulnagpal** [comment]
Sure, looking into it :+1:

**Comment by mridulnagpal** [comment]
http://leafletjs.com/reference-1.2.0.html#map-zoomsnap Is it this one?

**Comment by mridulnagpal** [comment]
I found something called the touch zoom, here http://leafletjs.com/reference-1.2.0.html#map-touchzoom setting it to center as well.
