### ISSUE TITLE
BlurredLocationDisplay

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#84]
I've been thinking, and I wanted to propose a change to the final stage of your work, if you're interested and you agree. 

We had discussed integrating this with PublicLab.org, but instead of working on that, I was thinking that it could be better to provide a new (fairly big) feature which would make it easier to use this on PublicLab.org, and to defer the integration steps for now. 

Once people enter a lot of blurred locations, we will need a way to display them, but as grid squares, you know? Like, let's say 20 people enter locations at varying levels of precision. How do we display them? Showing a marker at the "blurred" location is kind of misleading. Better, perhaps, to:

1. have a separate library or a feature of this library that can display a bunch of blurred locations on a Leaflet map
2. have it display a Graticule, and shade grid squares that contain one or more blurredLocation
3. when you click on a grid square containing blurred locations (i.e. grid square `40.01, 80.01` would include `40.015, 80.016` and `40.01065, 80.010632`), display a popup with a list of those locations that fall within the grid square
4. either don't display a `40.01` blurred location if your zoom level is currently to precision `0.001` (that is, more zoomed in) or, show that location for /all/ grid squares that overlap with the blurred location of lower precision (so, that location would show up multiple times)

This is a bit complex to think through, but I think implementation could actually be pretty easy. You could, for example, do (although this seems a bit messy):

```js
// this "constructs" an instance of the library at a center point:
var location = new BlurredLocation({
  lat: 41.01,
  lon: -85.66
});
location.mode('display'); // disable the location input mode; alternatively something like location.hideInput();
location.displayList([
  [35.35, 39.26, "Popup Text"],
  [35.35, 39.26, "Popup Text"]
]);
```

Something like that. You could try to follow syntax in http://leafletjs.com/examples/quick-start/, more or less. 

What do you think about this? I know it's a bit change to the end of the project, but I realized a means to display a map will be important to being able to use this library.

**Comment by mridulnagpal** [comment]
Sure, I can try it!!

**Comment by mridulnagpal** [comment]
What do you suggest a feature or a library by itself?

**Comment by jywarren** [comment]
Well, what do you think of my proposed method above? Can you initialize BlurredLocation() without providing the HTML inputs, and will it cause errors? I guess perhaps this is a different function and could be provided via a separate library to keep things really distinct. Which makes more sense to you?

**Comment by mridulnagpal** [comment]
For BlurredLocation() I need a number of html DOM elements I have set up inside of it, so yes it will give errors. Easier way would be adding it as a feature, but if you can think of any other I will be happy to learn!!

**Comment by mridulnagpal** [comment]
@jywarren So I looked into ways of making this work without html but couldn't. Should I make it as a new feature or do we need to stick to a different library only?

**Comment by jywarren** [comment]
What do you think of moving the constructor itself into a submethod like
BlurredLocation.Input() vs BlurredLocation.Layer()?

**Comment by jywarren** [comment]
Or if there really is no shared code between the input library (that you've
completed) and the new display library, let's make a separate lib called
BlurredLocationDisplay, what do you think?

**Comment by mridulnagpal** [comment]
Can you create a new repo for the same? For the new lib?

**Comment by mridulnagpal** [comment]
@jywarren What all things do you want me to do before the deadline, as I
recieved a mail from google regarding submission

**Comment by mridulnagpal** [comment]
@jywarren Haven't heard from you in a while so creating a repo on my own
and setting it up. Please reply ASAP


On 18-Aug-2017 2:28 PM, "Mridul Nagpal" <mridulnagpal07@gmail.com> wrote:

@jywarren What all things do you want me to do before the deadline, as I
recieved a mail from google regarding submission

**Comment by jywarren** [comment]
Please do, and call it Leaflet.BlurredLocationDisplay for now!

**Comment by jywarren** [comment]
Ok I did it!

https://github.com/publiclab/Leaflet.BlurredLocationDisplay

**Comment by mridulnagpal** [comment]
Thanks ! :)
