### ISSUE TITLE
Developing a button to display current latitude and longitude the current position of map is pointing to

### ISSUE THREAD

**Issue by mridulnagpal** [publiclab/leaflet-blurred-location#9]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!
blu
If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

# The Problem #

We have an API available to get the current lat and lon of the map. What we need to do is create a button for template here https://github.com/publiclab/leaflet-blurred-location/blob/master/examples/example.html which will be available as soon as #7 is merged. 

# Solution #

In the file example.html we need to add a button which when clicked alerts us with the lat, lon. The API reference is `blurredLocation.getLat()` and `blurredLocation.getLon()`   which would return the lat and lon respectively. blurredLocation is a Global object which controls the map. You need to get those co-ordinates from the API using `blurredLocation.getLat()` and `blurredLocation.getLon()`. And then display them to the user. It will be something like this in the example.html file.
`      <button onclick="displayLocation()">Location</button> `

And adding the function to object.js file

`function displayLocation() {
  if(blurredLocation) {
    var lat = blurredLocation.getLat();
    var lon = blurredLocation.getLon();
    alert(lat+','+lon);
  }
}`

Remember as soon as you make changes in object.js either run grunt build or have grunt watch running while you save changes, to test them.

## Steps to fix ##

- [x] claim this issue with a comment here, below, and ask any clarifying questions you need
- [x] set up a repository locally following the README instructions, and make sure that all tests pass
- [x] try to fix the issue following the steps above, but even before you're done, you can:
- [x] commit your changes and start a pull request (see contributing to Public Lab software) but mark it as "in progress" if you have questions or if you haven't finished
- [x] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

**Comment by mridulnagpal** [comment]
@jywarren If you could tag this, also can I merge PR's in this repo, I couldn't find out how to do it. Is there some privacy issue there, please let me know. Thanks!

**Comment by jywarren** [comment]
I'd still like to review PRs for the time being, so please be in communication before doing it, but i invited you to be a collaborator a while ago and I think you didn't click the invitation yet?

**Comment by jywarren** [comment]
I also think this one is totally ready to be a `help-wanted` issue, but not quite a `first-timers-only` issue. It may seem like a lot, but a true FTO issue can actually guide you step by step through the code that has to be added, on what line, linking to perhaps an example of how similar code looks like elsewhere. Think about it like a way to guide people through every step, just the first time, so they see the whole experience -- it's more about them going through the steps than about them solving an unsolved problem. Make sense?

If you could add a bit more detail i'll add the FTO label too!

**Comment by mridulnagpal** [comment]
Sorry for that, I'll more info to it.

**Comment by mridulnagpal** [comment]
@jywarren Please have a look

**Comment by mridulnagpal** [comment]
@jywarren I have added some more info to the issue, is it ready to be a first timer issue?

**Comment by jywarren** [comment]
I think it is but let's wait until #7 is merged and it is more possible for folks to get started. Great work!

**Comment by ananyo2012** [comment]
Can we add a `fto-candidate` label here?

**Comment by mridulnagpal** [comment]
Yeah sure !

On 27-Aug-2017 2:26 AM, "Ananyo Maiti" <notifications@github.com> wrote:

Can we add a fto-candidate label here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/leaflet-blurred-location/issues/9#issuecomment-325161470>,
or mute the thread

**Comment by warborn** [comment]
Hi, i would like to take this if it's still available, i set up the repo locally but i can't find the object.js file where the function should be added and examples.html file where the button should be added, for now, i added the changes to the examples/index.html file and maked them work as expected.

**Comment by mridulnagpal** [comment]
The code has been restructured a bit. You will need to add the `displayLocation()` method to src/blurredLocation.js which comprises of the main object blurredLocation, and then return the object adding the method to it, i.e for the last part in src/blurredLocation.js add the method to the object as follows:

`
return {
...
...
displayLocation: displayLocation,
}
'

**Comment by warborn** [comment]
Thanks for the info! I've created a new pull request
