### ISSUE TITLE
Be careful not to use variable name "location" -- it's a reserved word in JavaScript

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#91]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

We will need to change the README to avoid using `location` as that will change the URL of the page and direct the browser to load a different URL. 

## Solution

We need to change any instance of using simply `location` to `blurredLocation` in the README file, which is here:

https://github.com/publiclab/leaflet-blurred-location/blob/master/README.md

Thanks!

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by brissettdwayne** [comment]
I want to claim this issue.

**Comment by jywarren** [comment]
That'd be great! Please tell us if you have any questions! Thanks!
