### ISSUE TITLE
Map should show marker, not rectangle, when blurring is off

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#94]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

When you disable blurring, it should just show a single marker pegged to the center of the view frame, indicating the exact (unblurred) location. 

Right now it hides the grid but continues showing a square:

![screenshot 2017-09-29 at 10 26 57 am](https://user-images.githubusercontent.com/24359/31020386-d8a03838-a500-11e7-8f99-dc0259b88e25.png)

## Solution

This is managed in `setBlurred()`: https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L199-L208

I think `updateRectangleOnPan()` should be changed to not draw a rectangle if `isBlurred` is false.

Instead, it should ensure that a single marker is displayed, pegged to the center. Here's some sample code that may be a starting point: https://stackoverflow.com/questions/46004250/central-leaflet-marker-always-when-map-moves

Another way to solve this might be to actually display the Leaflet icon in HTML outside the map, and absolute-positioned. This could cause trouble if you resize the map (when the absolute positioning would have to change), but is worth considering and wouldn't have any "lag" from having to move the center point marker every time you drag. 

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by jywarren** [comment]
@mridulnagpal @ryzokuken could this make a good one for newcomers?

**Comment by mridulnagpal** [comment]
Yeah sure, something like enableCenterMarker on disabling isBlurred, sounds
about right?

**Comment by jywarren** [comment]
Yes!

**Comment by arjbholu** [comment]
I want to take this issue @jywarren .

**Comment by kidboyks** [comment]
Hi ,

Can I take up this issue?

Thanks,
Nikhil

**Comment by ryzokuken** [comment]
Hey, @kidboyks! Sure, go ahead. In case you face any issues, feel free to ask.

**Comment by kidboyks** [comment]
HI @ryzokuken,

I have modified the setBlurred to call updateRectangleOnPan(); Which enables and diisables the marker and the shade accordigly.

Thanks,
Nikhil

**Comment by kidboyks** [comment]
How do I push my code to this repo? I have my changes ready on local repo. Should I be creating a new branch?

**Comment by ryzokuken** [comment]
Yes. Update your master, make your changes on a branch and make a PR from your branch to our master. Thanks.

**Comment by kidboyks** [comment]
Apologies,

Looks like i have no permisions to create a new branch nor to push to an existing branch. Could you help me out.

Thanks

**Comment by ryzokuken** [comment]
@kidboyks you surely don't for this repository. You would need to fork this one and make changes to your own copy.

**Comment by kidboyks** [comment]
oh okay thank you :)

**Comment by jywarren** [comment]
Fixed in #97! Thank you so much, @kidboyks -- we're so happy to have your help. Do any other issues look interesting? 

https://github.com/publiclab/leaflet-blurred-location/issues

**Comment by kidboyks** [comment]
Thank you so much for making my first PR experience really smooth. Will
checkout the issues and let you know:)
