### ISSUE TITLE
Add +/- zoom buttons to Leaflet map

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#95]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

The map as it is now is hard to zoom around in on some interfaces (i.e. trackpad) , so let's add some zoom buttons, like on this Leaflet example:

http://leafletjs.com/examples/quick-start/

That example also says zoom controls should be on by default. Not sure why they aren't in this map! 

## Solution

Ah, so we have to remove the `{zoomControl: false}` part of this line:

https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L17

```js
options.map = options.map || new L.Map(options.mapID, { zoomControl: false }).setView([options.location.lat, options.location.lon], options.zoom);
```

I think we can just replace `{zoomControl: false}` with `{}`.

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by Bubblemelon** [comment]
Hi, I have not contributed to Public Lab before, and would like to claim this issue. :)

**Comment by Bubblemelon** [comment]
@jywarren I'm also wondering how you put the checkmark on the list item?

**Comment by Bubblemelon** [comment]
The checkmarks weren't clickable for me. 

Here are some articles about it that I thought were helpful:
[https://help.github.com/articles/about-task-lists/](https://help.github.com/articles/about-task-lists/)
[https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments)

**Comment by jywarren** [comment]
Hi! Yes please - we'd love your help. It's true, the checkboxes are not
💯... I can check them for you and/or invite u to be a contributor.
Thanks!!!

On Oct 24, 2017 6:15 PM, "Cheryl Fong" <notifications@github.com> wrote:

The checkmarks weren't clickable for me.

Here are some articles about it that I thought were helpful:
https://help.github.com/articles/about-task-lists/
https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/leaflet-blurred-location/issues/95#issuecomment-339151677>,
or mute the thread
