### ISSUE TITLE
truncate unblurred lat/lon to reasonable precision

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-blurred-location#99]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

## The problem

Currently we get 16 places of precision in latitude and longitude -- like `89.0023587573869784` -- which is FAR beyond any reasonable precision. We should return something more reasonable; 

~110,000 meters = 1 degree at the equator, so latitude of 1.000000 (six places) has precision of a meter. GPS is very rarely that precise, but six places seems much more reasonable than 16. 

## Solution

We could make that adjustment here: https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L54

and here: https://github.com/publiclab/leaflet-blurred-location/blob/master/src/blurredLocation.js#L61

using the same truncation as when `isBlurred` is true, but just to 6 places. 

## Steps to Fix

- [ ] claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to [the chatroom](http://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information](https://github.com/publiclab/plots2/projects/2)!

**Comment by fers490** [comment]
I would like to work on this one

**Comment by jywarren** [comment]
Nice! Solved by @fers490 in #100 -- thanks so much! 🎉
